### ISSUE TITLE
TypeString to TypeName Conversion?

### ISSUE THREAD

**Issue by stephensj2** [ConsenSys/solc-typed-ast#106]
## Description

I've been using this tool to instrument a contract with some new code. As part of this instrumentation I needed to elevate some code into its own function. In doing so I need to create appropriate function arguments/return values. However, expressions only provide a type string, rather than a TypeName, which seems to be required by a VariableDeclaration. Is there a way to convert a type string into a TypeName? I looked through the available docs and wasn't able to find anything.

**Comment by blitz-1306** [comment]
Hello there. You may try to use [`getNodeType()`](https://github.com/ConsenSys/solc-typed-ast/blob/e880b9d6abeefc1fd2da564699b6d25ba3c076b8/src/types/typeStrings/typeString_parser_header.ts#L90-L102).

**Comment by stephensj2** [comment]
Thanks for your quick response! I had looked at getNodeType which would convert into a TypeNode. From my understanding TypeNodes are a bit more precise than a TypeName as they can describe a broader variety of types. In this case, I would first convert to a TypeNode then essentially write a TypeNode to TypeName translator?

**Comment by blitz-1306** [comment]
This is one of the possible options, considering I do not have enough context on why do you need to have `TypeName`s.

**Comment by blitz-1306** [comment]
In most of the cases, primitive types are represented by `ElementaryTypeName`, or something like that. There are not so much type-related nodes in the original AST: https://github.com/ConsenSys/solc-typed-ast/tree/master/src/ast/implementation/type

**Comment by stephensj2** [comment]
Alright, this was helpful. Thanks!
