### ISSUE TITLE
Can it support saving the result of compileSol() to a local file, and ASTReader() read this local file to avoid compiling the sol file again?

### ISSUE THREAD

**Issue by smartcontract-detect-yzu** [ConsenSys/solc-typed-ast#141]
## Description
For a project, the output of compileSol() can be saved to a local JSON file. And when doing AST analysis, we just use the ASTReader() to load this local JSON file without compiling the project again.

## Context
The compile is too slow. And I need to do some syntax analysis for a smart contract based on its AST.

**Comment by blitz-1306** [comment]
Hello there, You can use [`compileJson()`](https://github.com/ConsenSys/solc-typed-ast/blob/9dee6b4bb1df6ee391b54fe6fe3bd3531edd31a5/src/compile/utils.ts#L430-L440) with solc-produced artifact. We do this in out tests to boost performance.

**Comment by smartcontract-detect-yzu** [comment]
> Hello there. You can use [`compileJson()`](https://github.com/ConsenSys/solc-typed-ast/blob/9dee6b4bb1df6ee391b54fe6fe3bd3531edd31a5/src/compile/utils.ts#L430-L440) with Solc-produced JSON artifact with an AST. We do this in out tests to boost performance.
> 
> Also you may consider to supply Solc-produced JSON artifact AST to [`ASTReader.read()`](https://github.com/ConsenSys/solc-typed-ast/blob/9dee6b4bb1df6ee391b54fe6fe3bd3531edd31a5/src/ast/ast_reader.ts#L188-L228) with few considerations.

Thanks for your kind reply.
