### ISSUE TITLE
CompileSol Fails when the compiled contract import a contract that import another contract

### ISSUE THREAD

**Issue by zian546** [ConsenSys/solc-typed-ast#148]
## Environment
Node: v16.15.0
solc-typed-ast:  v10.1.6

## Scenario
I'm building an app that involves modifying solidity AST. compileSol failed to compile
my contract when I import a contract *__that imports__* another contract.

I also tried to supply a base path in the ```pathOptions``` parameter and  *__it did__* work with the very first import. but from there I guess my supplied base path argument did not cover the relative path.

### index.ts
```typescript
private async compileContract() {
    try {
      let compile = await parser.compileSol(this.templateName, "auto", {
        basePath: __dirname,
      });
    } catch (e) {
      fs.writeFileSync("err.txt", e.toString(), "utf-8");
    }
  }
// this.templateName = "test.sol"
```

### test.sol
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract MyToken is ERC1155, Ownable {
    constructor() ERC1155("") {}

    function setURI(string memory newuri) public onlyOwner {
        _setURI(newuri);
    }
}

```

## Expected behavior
Should compile the contract successfully and provide the AST.

## Current behavior
I get over 800 lines of errors regarding file import callback not supported and all of them have a relative path prefix such as ```"./"``` ,```"../"```,```"../../"```,etc:
```bash
Error: Compiler Errors: ==== 0.8.15 ====:
 ParserError: Source "@openzeppelin/contracts/utils/Context.sol" not found: File import callback not supported
 --> @openzeppelin/contracts/access/Ownable.sol:6:1:
  |
6 | import "../utils/Context.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "@openzeppelin/contracts/token/ERC1155/IERC165.sol" not found: File import callback not supported
 --> @openzeppelin/contracts/token/ERC1155/..\..\utils\introspection\ERC165.sol:6:1:
  |
6 | import "./IERC165.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol" not found: File import callback not supported
 --> @openzeppelin/contracts/token/ERC1155/ERC1155.sol:8:1:
  |
8 | import "./extensions/IERC1155MetadataURI.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "@openzeppelin/contracts/utils/Address.sol" not found: File import callback not supported
 --> @openzeppelin/contracts/token/ERC1155/ERC1155.sol:9:1:
  |
9 | import "../../utils/Address.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "@openzeppelin/contracts/utils/Context.sol" not found: File import callback not supported
  --> @openzeppelin/contracts/token/ERC1155/ERC1155.sol:10:1:
   |
10 | import "../../utils/Context.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "@openzeppelin/contracts/utils/introspection/ERC165.sol" not found: File import callback not supported
  --> @openzeppelin/contracts/token/ERC1155/ERC1155.sol:11:1:
   |
11 | import "../../utils/introspection/ERC165.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by blitz-1306** [comment]
Hello there. Would it be possible to share directory structure, especially where Solidity files are located? Thanks in advance.

**Comment by blitz-1306** [comment]
Also, is `@openzeppelin` installed globally (on the system) or locally (in the project)? Is it local `node_modules/` or somewhere else?

**Comment by zian546** [comment]
Hello! Thank you for the reply.  I installed ```@openzeppelin``` locally in my project.  and I did move ```@openzeppelin``` to the root directory of my project. 

And below are my project directory structure:

![image](https://user-images.githubusercontent.com/67871461/187592495-83b3b21d-2165-45ae-9fd3-61ae2dbecfd3.png)

**Comment by blitz-1306** [comment]
Default import discovery logic tries to find dependencies under `node_modules`. In other cases you have to specify `PathOptions.remapping`. Your installation seem to be "specific" as `@openzeppelin/` looks like an absolute path.

What you can try:
- You could try to add `./` prefix before imports in `test.sol` -> `./@openzeppelin/...`.
- You could try to move `@openzeppelin/` into a `node_modules/` directory.
- You could try to specify `PathOptions.remapping` to set place where to look for `@openzeppelin` imports.

Regards.

**Comment by zian546** [comment]
I  see, Thank you for the suggestions. I'll try them shortly and come back here to tell the result.

**Comment by zian546** [comment]
yup adding the prefix fixed the issue. thank you!
