### ISSUE TITLE
Fix getABIEncoderVersion function

### ISSUE THREAD

**Issue by cd1m0** [ConsenSys/solc-typed-ast#167]
Currently the signature of the `getABIEncoderVersion` function computes one version for multiple source units:

```
export function getABIEncoderVersion(
    units: SourceUnit[],
    compilerVersion: string
): ABIEncoderVersion {
```

However this is incorrect. You can have in a **single** compilation, multiple source units with different `ABIEncoderVersion`s. To fix this we should:

1. Change the signature of `getABIEncoderVersion` to:

```
export function getABIEncoderVersion(
    units: SourceUnit,
    compilerVersion: string
): ABIEncoderVersion {
```

to force consumers of solc-typed-ast to deal with each unit separately.

2. Fix `getABIEncoderVersion` to handle the case when the `abicoder` pragma is in an imported unit

3. Add tests with:

3.1 One source unit with 2 conflicting encoder pragmas

3.2 One source unit with 2 non-conflicting (same) encoder pragmas

3.3 Source unit A, without a pragma, that imports unit B, with a pragma

3.4 Source unit A, with a pragma, that imports unit B, with a conflicting pragma

**Comment by blitz-1306** [comment]
Partially related to #169. Smells like a big change.
