### ISSUE TITLE
resolveAny() needs ABIEncoderVersion as well

### ISSUE THREAD

**Issue by cd1m0** [ConsenSys/solc-typed-ast#168]
We have currently hardcoded `ABIEncoderVersion.V2` inside `lookupInContractDefinition`. However this is potentially not compatible with older code. So we should find a way to pass in the abi version here.

 At first I thought we should just add abicoder version as a field to InferType.

However in a single compilation, you can have multiple SourceUnits with the same compiler version, but different ABI versions. So it doesn't seem like a good idea to keep it in InferType, since we were planning to have one InferType object per compilation.

So for now, as unpleasant as it is, perhaps we need to pass these manually?

Alternatively, we can try and add a computed getter on SourceUnit nodes that specifies their abi version. Then for any other node we can get the corresponding abi coder version by doing node.getClosestParentByType(SourceUnit).abiVersion. Not sure, we should discuss more. Probably file an issue.

Needs discussion

**Comment by blitz-1306** [comment]
Even if we make getter on `SourceUnit` level, we have to somehow pass values to `InferType` methods. Or compose multiple `InferType` (with added `encodeVersion` as a field or property) instances for each `SourceUnit`. This is debateable and also seem to be a compatibility break.

**Comment by cd1m0** [comment]
> Even if we make getter on `SourceUnit` level, we have to somehow pass values to `InferType` methods. Or compose multiple `InferType` (with added `encodeVersion` as a field or property) instances for each `SourceUnit`. This is debateable and also seem to be a compatibility break.

If we add a getter to `SourceUnit` for the abi version, I don't think we need to add an argument to `InferType`. Instead when we ask for `typeOf(A)` where A is an `ASTNode`, we get the abi version from `A.getClosestParentByType(SourceUnit).abiVersion`. And if there is no `SourceUnit` parent (e.g. A is an orphan/detched child), then we just assume V2 by default. Or throw an exception?

**Comment by cd1m0** [comment]
But yeah, its starting to feel that adding the argument to `InferType` is the cleaner solution. More work for consumers, but it forces them to be explicit
