### ISSUE TITLE
Fix hack in InferTypes that converts calldata in function types to memory

### ISSUE THREAD

**Issue by cd1m0** [ConsenSys/solc-typed-ast#196]
Originally in InferType we had a hack in `typeOfMemberAccessImpl` that converted all calldata locations in a function type to memory. This hack was there so that the return types of an external function call would be inferred as memory rather than calldata. However this is incorrect, and is causing failures in other clients.

The correct behavior is to infer the calldata locations of the callee, and to change the location from calldata -> memory iniside `typeOfFunctionCall` instead, reflecting the implicit cast that Solidity does.

**Comment by blitz-1306** [comment]
This is fixed by #197. Closing as resolved.
