### ISSUE TITLE
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of ArrayBuffer

### ISSUE THREAD

**Issue by Muhammad-Altabba** [Consensys/solc-typed-ast#211]
## Environment

solc-typed-ast version: `15.0.0`.
node version: `16.16.9`.
typescript version: `4.9.3`.

## Scenario
```ts
import { compileSol } from "solc-typed-ast";

export async function compile (){
  const result = await compileSol("./src/sample.sol", "auto");
  console.log(result);
  return result;
}
```

## Current behavior
The following error is reported:
```bash
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of ArrayBuffer
        at new NodeError (node:internal/errors:372:5)
        at Hash.update (node:internal/crypto/hash:105:11)
        at getCompilerForVersion (/home/maltabba/repos/experiments/web3-abi-generator/node_modules/solc-typed-ast/src/compile/kinds/compiler.ts:141:14)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at compile (/home/maltabba/repos/experiments/web3-abi-generator/node_modules/solc-typed-ast/src/compile/utils.ts:154:22)
        at compileSol (/home/maltabba/repos/experiments/web3-abi-generator/node_modules/solc-typed-ast/src/compile/utils.ts:326:22) {
      code: 'ERR_INVALID_ARG_TYPE'
    }
```

## Description [optional]

https://github.com/nodejs/node/blob/49a77a5a996a49e8cb728eed42e55a7c1a9eef6e/lib/internal/crypto/hash.js#L105

## Suggested solution [optional]
Use `"string"` instead of `"arraybuffer"` at this line:
https://github.com/ConsenSys/solc-typed-ast/blob/63828e53551f1a61b4a71103aaa4eeab4f6d9173/src/compile/kinds/compiler.ts#L136

**Comment by blitz-1306** [comment]
@Muhammad-Altabba Hello there. I will investigate the issue and currently opened pull request with fix. Will respond with results when there would be any information to share. Thank you.

**Comment by blitz-1306** [comment]
@Muhammad-Altabba Hello again. I checked the possible issue, but not yet able to reproduce it on my end.

First of all, I didn't found NodeJS **v16.16.9** release. So I tried to downgrade to **v16.14.0** instead. In this version, there is no conflict in typesystem. TypeScript compiler invocation (via `tsc`) still manages to compile the codebase.

I also checked through documentation for [a particular release](https://nodejs.org/dist/v16.14.0/docs/api/crypto.html#hashupdatedata-inputencoding). It seems that the crypto API supports `Buffer` (that is returned by axios request). Also I do not see any related failures in our CI anywhere, except your opened PR (that is failing).

The kind of problem, that you expressing, regularly related to a difference in environment. Could you, please, doublecheck the environment where you experiencing issue? Is it related to NodeJS of Browser?

**Comment by Muhammad-Altabba** [comment]
@blitz-1306 ,
Sorry for the typo regarding the node version. I used `16.16.0`. But I am still facing the same issue after I downgraded to version 16.14.0.

And I fixed the MR. And I hope they will pass after you approve the workflow to run.

Regarding the environment, I am using node and not the browser.

**Comment by blitz-1306** [comment]
@Muhammad-Altabba Hello there. I pulled the mentioned repository, removed `.skip` suffix from tests. Comple test succeeded for me without any issues. I'm currently running NodeJS `v16.14.0`. Maybe it is something in your environment.

**Comment by blitz-1306** [comment]
It would be great if you will be able to make CI work to show the issue there. If issue would manifest in clean environment it would be easier to catch and fix.

**Comment by Muhammad-Altabba** [comment]
Hi @blitz-1306 ,
I am still facing the issue locally. And the CI used to pass but is now failing at https://github.com/conx3/web3-plugin-craftsman
I suggest that it could be something wrong with the server deployment. If I could guess there are multiple servers that are supposed to serve the exact same version but they are not.Or what do you think?

**Comment by blitz-1306** [comment]
@Muhammad-Altabba

Hello there.

First of all, sorry for late response - I took some time for vacation and was dedicated to issues IRL.

I looked through mentioned jobs and was finally able to reproduce the issue. I created a small PR #216 with possible fix. Could I ask you to help checking that things are smooth with these fixes on your end (at least locally)?

Following steps are needed:
- In **solc-typed-ast** repo clone, switch to https://github.com/Consensys/solc-typed-ast/tree/fix-downloading-for-newer-nodejs branch. Then perform local installation with commands:
```bash
npm install
npm link
```
- Remove any predownloaded compilers, that may be present in compiler cache. You can discover cache location by running command:
```bash
sol-ast-compile --locate-compiler-cache
```
- In repos with mentioned issues tweak `package.json` to use local **solc-typed-ast** like following:
```js
"dependencies": {
  "solc-typed-ast": "file:path/to/solc-typed-ast/"
  // ...
}
```
Then try to run package build steps and testing them.

I also seen that you try to run package on Windows-based hosts. Beware that we had issues with it and do not yet fully support this platform. I had a few attempts in #177, but this for now is out of our priority list.

**Comment by Muhammad-Altabba** [comment]
Hello @blitz-1306,
Sorry also for the late reply :)

I followed the steps and yes it worked.

And I am not currently running on Windows-based hosts. But I thought and now I hope that it will be supported in the future :)

**Comment by blitz-1306** [comment]
Next release should have a in it, as #216 is merged.
