### ISSUE TITLE
Add support for computing file-level constants

### ISSUE THREAD

**Issue by cd1m0** [Consensys/solc-typed-ast#224]
Solc-typed-ast currently has support for computing constant expressions (e.g. `(123+67)/10`). We would like to add something similar, that allows us to compute the values of Solidity file-level constants. File-level constants are more complicated than constant expressions, since they can include:

- Identifier (other file-level constants)
- Member Accesses (other file-level constants referred to as Module.Constant)
- Index Accesses (indexing into another bytes file-level constant).
- Conditionals
- Type-casts

You can see an example of each of these cases in this sample:

```solidity
import "./FileLevelConstants075_lib.sol";
import "./FileLevelConstants075_lib.sol" as Lib;

uint constant SOME_CONST = 100;
uint constant SOME_OTHER = 15;
uint constant SOME_ELSE = SOME_CONST + SOME_OTHER;
uint constant C2 = SOME_ELSE + ANOTHER_CONST;
uint constant C3 = SOME_ELSE + Lib.ANOTHER_CONST;
uint constant C4 = - SOME_CONST;
bool constant C5 = false;
uint constant C6 = C5 ? C2 : C3;

string constant FOO = "abcd";
bytes constant BOO = bytes("abcd");
bytes1 constant MOO = BOO[0];
```

The concrete outcome will be a new interface

```typescript
export function evalFileConstant(node: VariableDeclaration, inference: InferType): Value
```

The interface is similar to `evalConstantExpr` but handles the additional cases outlined above.

**Comment by blitz-1306** [comment]
I managet to tweak original functions `isConstant()` and `evalConstantExpr()` to handle file-level constants too. I do not yet think that we need an additional function yet (as current one handles same cases).
