### ISSUE TITLE
evalLiteral crashes on certain strings

### ISSUE THREAD

**Issue by cd1m0** [Consensys/solc-typed-ast#227]
Given the string: `"\x75\x32\xea\xac"`, `evalLiteral` will return null, thus causing a crash.

It seems that for this literal, the `kind` is 'string' but the `value` is `null` and the `hexValue` contains the actual string. So in `evalLiteral` we will pass `null` to `evalLiteralImpl`:

```
export function evalLiteral(node: Literal): Value {
    try {
        return evalLiteralImpl(
            node.kind,
            node.kind === LiteralKind.HexString ? node.hexValue : node.value,
            node.subdenomination
        );
        ...
```

**Comment by blitz-1306** [comment]
#225 now also respects this edge-case
