### ISSUE TITLE
Declaring a top-level `payable` constant results in `CompileInferenceError`

### ISSUE THREAD

**Issue by gas1cent** [Consensys/solc-typed-ast#255]
## Environment

Latest release, v18.1.1

## Scenario

When a `payable` constant is defined outside of a contract, the compiler throws a `CompileInferenceError`. No error is thrown in the same scenario but without `payable`.

To test put the following in `sample.sol`:
```
pragma solidity 0.8.24;
address payable constant SWAPROUTER_ADDRESS = payable(0xE592427A0AEce92De3Edee1F18E0157C05861564);
```

Then try to compile:
```
import { compileSol} from 'solc-typed-ast';
const result = compileSol('./sample.sol', 'auto');
```

## Expected behavior

Successful compilation.

## Current behavior

```
CompileInferenceError: Failed parsing imports at ./sample.sol:65:1 - Expected " ", "/*", "//", "[", "\t", "\x0B", "\x0C", "constant", " ", "", [ , , , - , , ,　], or [\n,\r,,] but "p" found.
    at findAllFiles (/node_modules/solc-typed-ast/src/compile/inference/imports.ts:171:23)
    at compileSol (/node_modules/solc-typed-ast/src/compile/utils.ts:317:27)
```

**Comment by gas1cent** [comment]
Hey @blitz-1306, pinging you because you've helped us before. Any chance you could take a look at this issue? Huge thanks in advance 🙏🏻

**Comment by blitz-1306** [comment]
@gas1cent Hello there and thanks for the input. I will look into it and provide feedback on this week. If there would be a fix, it would likely arrive on next week.

**Comment by blitz-1306** [comment]
Okay, this is clearly a bug related ty file-level definitons parser, that we use to preprocess imports. I will look into a possible solution. Stay tuned.

**Comment by blitz-1306** [comment]
See #256 with the bugfix. I believe we should be able to deliver it soon enough.

**Comment by blitz-1306** [comment]
@gas1cent Release [v18.1.2](https://github.com/Consensys/solc-typed-ast/releases/tag/v18.1.2) is out. Feel free to test. Thank you.
