### ISSUE TITLE
Add support for Solidity 0.8.26

### ISSUE THREAD

**Issue by beeb** [Consensys/solc-typed-ast#266]
## Description

It would be good to support Solidity 0.8.26.

## Context

Solidity 0.8.26 introduces new syntax for `require` statements, where the second parameter can now be a custom error.

[Release notes](https://soliditylang.org/blog/2024/05/21/solidity-0.8.26-release-announcement)

**Comment by cd1m0** [comment]
Working on it! Thank you for pointing out!

**Comment by cd1m0** [comment]
Fixed in #271
