### ISSUE TITLE
Hello, can you tell us how the node types in the AST node type list are defined? Thank you

### ISSUE THREAD

**Issue by freesytle** [Consensys/solc-typed-ast#268]
Hello, can you tell us how the node types in the AST node type list are defined? Thank you

**Comment by cd1m0** [comment]
Sorry could you give me a bit more context on your question? Which node type list are you referring to? Do you have a code sample /ast example on which we can discuss? Thank you!

**Comment by freesytle** [comment]
Thank you very much for your answer. This is the list of nodes you provided: [NODE_LIST.md](https://github.com/ConsenSys/solc-typed-ast/blob/master/NODE_LIST.md). 

I want to know how the node types of the AST are defined in Solidity. Looking forward to your reply. Thank you very much!

**Comment by cd1m0** [comment]
These are the node types that are returned by the Solidity compiler. They are defined by the grammar here https://docs.soliditylang.org/en/latest/grammar.html. Each node type corresponds to a production rule in the grammar with (almost) the same name. The node type should have the same name as the rule, after removing the dashes and changing to caml case. I hope this answers your question. If not, please feel free to re-open

**Comment by freesytle** [comment]
Thank you very much for your answer, another question, I want to get the control flow diagram and data flow diagram from the source code, which is very important for my experiment, if you can tell me how to do it, I would be very grateful.

**Comment by cd1m0** [comment]
This is not currently supported by solc-typed-ast. If you want a control flow and/or data flow you would have to implement it yourself. Also control flow and data flow are outside of the scope of solc-typed-ast. If you decide to implement this, it might make sense to build it as a separate library on top of solc-typed-ast
