### ISSUE TITLE
Two questions - installation and exporting solc-typed-ast.

### ISSUE THREAD

**Issue by appff** [ConsenSys/solc-typed-ast#3]
1. I tried to install solc-typed-ast using 'npm install -g @consensys/solc-typed-ast' but npm presented an error message
   - '@consensys/solc-typed-as' is not in the npm registry.
   - how to solve the issue?

2. Can I get a JSON output of solc-typed-ast like "solc --json-ast"

Thanks.

**Comment by blitz-1306** [comment]
Hello there and thanks for the feedback.

The first issue `'@consensys/solc-typed-as' is not in the npm registry` is probably caused that the package is not yet published in npm. This would be done in the near future. As a workaround you can try to clone the repository and build it from source:
```console
git clone https://github.com/ConsenSys/solc-typed-ast.git
npm install
npm link
sol-ast-compile --version
```
That should give following output:
```
3.0.3
```
Then you will be able to use following command to get the _raw_ compiler JSON:
```
sol-ast-compile path/to/input.sol --raw
```
Note that typed universal AST is not exported as JSON. Will get the output of the SolcJS compiler by this command.

**Comment by appff** [comment]
thanks!
